name: Deploy to Staging
on:
  push:
    branches: [main]
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOST }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@51.20.80.128 -t "cd excalidraw/ && git pull origin main && source ~/.bashrc && npm install -g pnpm && pnpm install &&  pnpm run build && pm2 restart fe && pm2 restart http-server && pm2 restart ws-server"
         
          
          
          
          
           
